### ISSUE TITLE
calling Telescope built-in picker moves cursor to the left by one

### ISSUE THREAD

**Issue by zijian-x** [nvim-telescope/telescope.nvim#1185]
### Description

After mapping `<esc>` to exit Telescope picker and calling e.g. `:Telescope find_files` or any other built-in picker, the cursor will be shifted to the left by one.

### Neovim version

NVIM v0.6.0-dev+205-g9695691ee

### Operating system and version

Linux arch 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux

### Steps to reproduce

example having a line "foobar":
```
foobar
cursor at 'r'
:Telescope find_files
exit picker either by pressing <esc> or <c-[>
now cursor at 'a'
```

### Expected behavior

Cursor does not move.

### Actual behavior

Moves one to the left.

### Minimal config

```Lua
call plug#begin('$XDG_DATA_HOME/nvim/site/plugged')
	Plug 'nvim-lua/popup.nvim'
	Plug 'nvim-lua/plenary.nvim'
	Plug 'nvim-telescope/telescope.nvim'
call plug#end()

lua << EOF
require('telescope').setup{
	defaults = { mappings = { i = { ["<esc>"] = require('telescope.actions').close, }, }, },
}
EOF
```

**Comment by ajitid** [comment]
This also happens if one selects a file from the list using enter key. To easily reproduce it, install a plugin which can restore cursor like https://github.com/farmergreg/vim-lastplace and perform  `Telescope find_files` once and `:e <filename>` the other time after reopening nvim.

**Comment by Conni2461** [comment]
Can someone confirm that this has been fixed? I can no longer reproduce this

**Comment by fdschmidt93** [comment]
Just rebased to latest master and doesn't seem to be fixed for me:

1. Open nvim
2. Type "this", cursor on "s"
3. `:Telescope find_files"
4. `<C-c>`
5. Cursor on i

I'm pretty confident this still persists since it's among our favorite mode switching issues (i.e. escape picker in normal mode doesn't have that issue).

**Comment by Conni2461** [comment]
uff i zoned out and tested if the bug is still a thing with your fix LUL. Found other issues, reported in PR
