### ISSUE TITLE
attempt to call field 'ft_to_lang' (a nil value)

### ISSUE THREAD

**Issue by daveyarwood** [nvim-telescope/telescope.nvim#3487]
### Description

Since updating my Neovim packages recently, I have been getting this error when opening the Git Files dialog and then on every key press.

### Neovim version

```markdown
NVIM v0.11.2
Build type: Release
LuaJIT 2.1.1748459687
```

### Operating system and version

macOS Sonoma 14.6.1

### Telescope version / branch / rev

0.1.x branch

### checkhealth telescope

```markdown
telescope:
   1 ⚠️

Checking for required plugins
- ✅ OK plenary installed.
- ✅ OK nvim-treesitter installed.

Checking external dependencies
- ✅ OK rg: found ripgrep 14.1.1
- ⚠️ WARNING fd: not found. Install [sharkdp/fd](https://github.com/          sharkdp/fd) for extended capabilities

===== Installed extensions =====

- ✅ OK lib working as expected
- ✅ OK file_sorter correctly configured
- ✅ OK generic_sorter correctly configured
```

### Steps to reproduce

Have `fzf` installed. I have version 0.62.0 from Homebrew.

Have the following telescope plugins installed:

```vimscript
Plug 'nvim-telescope/telescope.nvim', { 'branch': '0.1.x' }
Plug 'nvim-telescope/telescope-fzf-native.nvim', { 'do': 'make' }
Plug 'nvim-telescope/telescope-symbols.nvim'
```

Here is my Telescope config:

```lua
local telescope = require("telescope")
local builtin = require("telescope.builtin")

telescope.setup {
  pickers = {
    buffers = { theme = "ivy" },
    diagnostics = { theme = "ivy" },
    find_files = { theme = "ivy" },
    git_files = { theme = "ivy" },
    help_tags = { theme = "ivy" },
    keymaps = { theme = "ivy" },
    live_grep = { theme = "ivy" },
    lsp_references = { theme = "ivy" },
    lsp_workspace_symbols = { theme = "ivy" },
    symbols = { theme = "ivy" },
  }
}

-- Extensions

telescope.load_extension("fzf")

-- Mappings (abbreviated)

vim.keymap.set('n', "<c-f>", builtin.git_files)
```

Attempt to use mapping to run the `git_files` builtin.

### Expected behavior

No errors, can use `fzf` to select a file from the repo to edit.

### Actual behavior

I can use `fzf` to select a file from the repo to edit and it works as expected, however I get the error below when opening the picker and on every key press.

# Stack trace

```
Error executing vim.schedule lua callback: ...bundle/telescope.nvim/lua/telescope/previewers/utils.lua:135: attempt to call field 'ft_to_lang' (a nil v
alue)
stack traceback:
        ...bundle/telescope.nvim/lua/telescope/previewers/utils.lua:135: in function 'ts_highlighter'
        ...bundle/telescope.nvim/lua/telescope/previewers/utils.lua:119: in function 'highlighter'
        ...scope.nvim/lua/telescope/previewers/buffer_previewer.lua:247: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

# Screenshot

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/c8c3f11b-bba9-41df-a3a5-6fc2783217e9" />

### Minimal config

```Lua
See above.
```

**Comment by kytpbs** [comment]
Having the exact same issue, I thought I had broken something myself and was trying to fix my config for the last 3 hours...

**Comment by broken-wheel** [comment]
I had the same issue. Looks like the problem is because of the difference between `nvim-treesitter`'s `main` vs. `master`, `0.10.0`etc.
## `main`:
https://github.com/nvim-treesitter/nvim-treesitter/blob/main/lua/nvim-treesitter/parsers.lua
```
---@type nvim-ts.parsers
return {
  ada = {
    install_info = {
      revision = 'e8e2515465cc2d7c444498e68bdb9f1d86767f95',
      url = 'https://github.com/briot/tree-sitter-ada',
    },
    maintainers = { '@briot' },
    tier = 2,
  },
...
```
## `0.10.0`:
https://github.com/nvim-treesitter/nvim-treesitter/blob/v0.10.0/lua/nvim-treesitter/parsers.lua
```
local api = vim.api
local ts = vim.treesitter

for ft, lang in pairs {
  automake = "make",
  javascriptreact = "javascript",
  ecma = "javascript",
  jsx = "javascript",
  gyp = "python",
  html_tags = "html",
  ["typescript.tsx"] = "tsx",
  ["terraform-vars"] = "terraform",
  ["html.handlebars"] = "glimmer",
...
```

So, using `v0.10.0` worked
* Lazy config
```lua
	{ "nvim-treesitter/nvim-treesitter", tag = "v0.10.0", lazy = false, build = ":TSUpdate" },
```
* Plugin setup
```lua
local configs = require("nvim-treesitter.configs")

configs.setup({
	ensure_installed = {
		"python",
		"cpp",
		"c",
		"proto",
		"dockerfile",
		"starlark",
		"bash",
		"javascript",
		"lua",
	},
	sync_install = false,
	highlight = { enable = true },
	indent = { enable = false },
})
```

**Comment by genericCandy** [comment]
I'm having the same issue, is there a way around it while still using the `main` branch of `nvim-treesitter`, or should i just switch to `master` ?

**Comment by calebsb3** [comment]
From what I could find, the ft_to_lang method was being used for highlighting in telescope's preview. Thus, a quick fix that I implemented to kind of bypass the warning is to disable treesitter for the preview screen using this 
```
require("telescope").setup({
  defaults = {
    preview = {
      treesitter = false,
    },
  },
})
```

Personally, I just added the preview section because I already had some defaults setup for telescope. This was more convenient for me than downgrading treesitter to 0.10.0

**Comment by Juhan280** [comment]
You are in the wrong branch of telescope. I am assuming you got this branch (0.1.x) from that latest tag release (0.1.8). There is no further development happening on that branch. Switch to master branch instead. It is already fixed in this commit https://github.com/nvim-telescope/telescope.nvim/commit/d8c5ed4e407c5c0a347d74ea091c3d56fbb2e7f2

**Comment by daveyarwood** [comment]
So I guess [this part of the README](https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#installation) is no longer accurate?

<img width="982" height="373" alt="Image" src="https://github.com/user-attachments/assets/ac926138-6981-47e3-ab32-c58110d3f5d8" />

**Comment by daveyarwood** [comment]
Confirmed that removing the plugin and reinstalling from the `master` branch fixed my issue.

**Comment by Juhan280** [comment]
> So I guess [this part of the README](https://github.com/nvim-telescope/telescope.nvim?tab=readme-ov-file#installation) is no longer accurate?
> 
> <img width="982" height="373" alt="Image" src="https://github.com/user-attachments/assets/ac926138-6981-47e3-ab32-c58110d3f5d8" />

Considering the fact that the commit I linked is 2 and half years old and its still not in a release tag, we can assert that this part of the readme is indeed incorrect

**Comment by daveyarwood** [comment]
It seems clear that `master` is actually the right branch to use, and the issue is fixed there, so closing this.

**Comment by AmmoniumX** [comment]
> It seems clear that `master` is actually the right branch to use, and the issue is fixed there, so closing this.

It wasn't clear to me, I followed the README to a t, which specifically states:

> It is suggested to either use the latest release [tag](https://github.com/nvim-telescope/telescope.nvim/tags) or our release branch (which will get consistent updates) [0.1.x](https://github.com/nvim-telescope/telescope.nvim/tree/0.1.x).

> It is not suggested to run latest master.

...and all the examples show you how to install tag/branch 0.1.8/0.1.x with different package managers, none recommend `master`

This issue is the first source I see that says `master` is now the recommended branch.
Might be worth it to change the README if that is not the case.

**Comment by mustafaergul** [comment]
Switching to master branch fixed the issue for me but not sure why i was in `0.1.x` 😄
